import test from "node:test";
import assert from "node:assert/strict";
import {spawnSync} from "node:child_process";
import {fileURLToPath} from "node:url";
import {dirname,join,resolve} from "node:path";
import {mkdirSync,unlinkSync,writeFileSync} from "node:fs";
import {redactCli} from "../build/cliRedaction.js";
import {EXIT} from "../build/centinela.js";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"../..");
const run=(args=[],env={})=>spawnSync(resolve(root,"scripts/centinela"),args,{cwd:root,encoding:"utf8",env:{...process.env,NO_COLOR:"1",...env},timeout:30_000});
test("help/version",()=>{assert.equal(run(["--help"]).status,0);assert.equal(run(["--version"]).status,0)});
test("unknown is 2",()=>assert.equal(run(["comando-inexistente"]).status,2));
test("stable JSON omits environment",()=>{const r=run(["status","--json"],{MEDOS_SYNTHETIC_PASSWORD:"do-not-print-synthetic"});assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).command,"status");assert(!r.stdout.includes("do-not-print-synthetic"))});
test("redaction",()=>{const c=redactCli("Authorization: Bearer synthetic.header.value token=synthetic-value postgres://user:pass@example.invalid/db sk-synthetic-1234");assert(!c.includes("synthetic-value"));assert(!c.includes("user:pass"));assert(!c.includes("synthetic-1234"))});
test("informational without vault",()=>{for(const a of [["status"],["vault","status"],["auth","status"],["n8n","status"],["backup","status"],["recovery","status"]])assert.equal(run(a).status,0,a.join(" "))});
test("fail closed",()=>{assert.equal(run(["backup","create"]).status,5);assert.equal(run(["vault","select"]).status,4);assert.equal(run(["emergency-lock"]).status,4)});
test("reject public binds",()=>{assert.equal(run(["start","launcher"],{MEDOS_BIND_HOST:"0.0.0.0"}).status,3);assert.equal(run(["start","launcher"],{MEDOS_BIND_HOST:"::"}).status,3)});
test("checkpoint inert",()=>{const before=run(["version"]).stdout;assert.equal(run(["checkpoint","--message","synthetic checkpoint"]).status,0);assert.equal(run(["version"]).stdout,before)});
test("exit contract",()=>assert.deepEqual(EXIT,{OK:0,GENERAL:1,ARGUMENTS:2,BLOCKED:3,HUMAN:4,VAULT:5,DEPENDENCY:6,UNHEALTHY:7,DIRTY:8,SECRET:9,REMOTE:10}));
test("NO_COLOR",()=>assert(!run(["status"],{NO_COLOR:"1"}).stdout.includes("\u001b[")));

test("stop rejects a foreign PID",()=>{const pidDir=join(root,"runtime","pids"),pidFile=join(pidDir,"launcher.pid");mkdirSync(pidDir,{recursive:true,mode:0o700});writeFileSync(pidFile,`${process.pid}\n`,{mode:0o600});try{const r=run(["stop","launcher"]);assert.equal(r.status,0);assert(process.kill(process.pid,0))}finally{try{unlinkSync(pidFile)}catch{}}});
