const sections=["Mi día","Chat","Pacientes","Expedientes","Agenda","Proyectos","Tareas","Correos","Investigación","Contabilidad","Documentos","Conocimiento","Traducciones","Redes sociales","Reputación","Automatizaciones","Seguridad","Casos forenses","Backups","Cuentas conectadas","Configuración","Emergencia"];
const nav=document.querySelector("#nav");const mobile=document.querySelector("#mobile-nav");
for(const [index,name] of sections.entries()){const button=document.createElement("button");button.className=`nav-item${index===0?" active":""}`;button.textContent=name;button.type="button";button.addEventListener("click",()=>showSection(name));nav.append(button);}
for(const name of ["Mi día","Chat","Proyectos","Seguridad"]){const button=document.createElement("button");button.textContent=name;button.type="button";button.addEventListener("click",()=>showSection(name));mobile.append(button);}
function showSection(name){document.querySelector("h1").textContent=name==="Mi día"?"Buen día, Dr. Jovani":name;document.querySelectorAll(".nav-item").forEach(item=>item.classList.toggle("active",item.textContent===name));}
async function loadState(){const response=await fetch("/api/state",{cache:"no-store"});const state=await response.json();document.querySelector("#done").replaceChildren(...state.done.slice(0,3).map(item=>Object.assign(document.createElement("li"),{textContent:item})));document.querySelector("#pending").replaceChildren(...state.pending.slice(0,3).map(item=>Object.assign(document.createElement("li"),{textContent:item})));document.querySelector("#now").textContent=state.now.title??state.now.firstStep;document.querySelector("#project-count").textContent=String(state.projects);}
function addMessage(text,type){const item=document.createElement("div");item.className=type;item.textContent=text;document.querySelector("#messages").append(item);item.scrollIntoView({block:"nearest"});}
async function send(message){addMessage(message,"user");const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json","X-Sentinel-Intent":"local-ui"},body:JSON.stringify({message})});const result=await response.json();addMessage(`${result.status??"PENDIENTE"}: ${result.message??"Solicitud rechazada"}\nAHORA: ${result.nextAction??"Revisar"}`,"assistant");}
document.querySelector("#chat-form").addEventListener("submit",event=>{event.preventDefault();const input=document.querySelector("#message");const value=input.value.trim();if(value){input.value="";send(value);}});
document.querySelectorAll("[data-command]").forEach(button=>button.addEventListener("click",()=>send(button.dataset.command)));
document.querySelector("#continue").addEventListener("click",()=>send("continuar"));
document.querySelector("#theme").addEventListener("click",()=>{const root=document.documentElement;root.dataset.theme=root.dataset.theme==="light"?"dark":"light";});
document.querySelector("#details").addEventListener("click",event=>{const panel=document.querySelector("#detail-panel");panel.hidden=!panel.hidden;event.currentTarget.setAttribute("aria-expanded",String(!panel.hidden));});
if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
loadState().catch(()=>addMessage("PENDIENTE: no pude cargar el estado local.","assistant"));
